export enum IconName {
  EyeOpen = 'eye-open',
  EyeClosed = 'eye-closed',
  Envelope = 'envelope',
  Lock = 'lock',
  CheckCircle = 'check-circle',
  XCircle = 'x-circle',
  X = 'x',
  ArrowRight = 'arrow-right',
  ArrowLeft = 'arrow-left',
  Logout = 'logout',
  CheckIn = 'check-in',
  CheckOut = 'check-out',
  Dashboard = 'dashboard',
  Users = 'users',
  Loading = 'loading',
  Phone = 'phone',
  User = 'user',
  Card = 'card',
  Clock = 'clock',
  ChevronDown = 'chevron-down',
  Briefcase = 'briefcase',
  Ticket = 'ticket',
  Calendar = 'calendar',
  Chart = 'chart',
}

export type IconNameType = `${IconName}`;
